import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { mapSkillToTool } from "../transformer/tool-mapper.js";
import { parseInputPath } from "../parser/parse-input.js";
import type { ParseDiagnostic } from "../ir/types.js";
import type { BuildArtifact, BuildCommandOptions, BuildResult, TransportMode } from "./types.js";
import { jsonSchemaPropertiesToZodObject } from "./schema-to-zod.js";

function toSafeIdentifier(input: string): string {
  const normalized = input.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  const startsWithDigit = /^[0-9]/.test(normalized);
  return startsWithDigit ? `tool_${normalized}` : normalized || "tool_handler";
}

function buildToolsJson(tools: BuildResult["tools"]): string {
  return `${JSON.stringify({ tools }, null, 2)}\n`;
}

function buildPackageJson(defaultTransport: TransportMode): string {
  const payload = {
    name: "generated-skill2mcp-server",
    version: "0.1.0",
    private: true,
    type: "module",
    license: "MIT OR Apache-2.0",
    scripts: {
      build: "tsc -p tsconfig.json",
      dev: "tsx src/server.ts",
      "start:stdio": "node dist/server.js --transport stdio",
      "start:http": "node dist/server.js --transport http",
      "start:both": "node dist/server.js --transport both",
      start: `node dist/server.js --transport ${defaultTransport}`,
    },
    dependencies: {
      "@modelcontextprotocol/sdk": "^1.29.0",
      zod: "^3.25.76",
    },
    devDependencies: {
      "@types/node": "^24.7.2",
      tsx: "^4.20.6",
      typescript: "^5.9.3",
    },
  };

  return `${JSON.stringify(payload, null, 2)}\n`;
}

function buildTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        rootDir: "src",
        outDir: "dist",
        strict: true,
        skipLibCheck: true,
        esModuleInterop: true,
      },
      include: ["src/**/*.ts"],
    },
    null,
    2,
  ).concat("\n");
}

function buildReadme(defaultTransport: TransportMode): string {
  return `# Generated skill2mcp MCP Server

This package was generated by \`skill2mcp build\`.

## Run

- Install dependencies: \`npm install\`
- Development: \`npm run dev\`
- Build: \`npm run build\`
- Start default transport (${defaultTransport}): \`npm start\`
- Start stdio: \`npm run start:stdio\`
- Start HTTP: \`npm run start:http\`

HTTP endpoint: \`POST /mcp\`
`;
}

function buildHandlersIndex(toolNames: string[]): string {
  const imports = toolNames
    .map((toolName) => {
      const safe = toSafeIdentifier(toolName);
      return `import { ${safe} } from "./${safe}.js";`;
    })
    .join("\n");

  const entries = toolNames
    .map((toolName) => {
      const safe = toSafeIdentifier(toolName);
      return `  ${JSON.stringify(toolName)}: ${safe},`;
    })
    .join("\n");

  return `${imports}

export interface ToolHandlerContext {
  toolName: string;
}

export type ToolHandler = (args: unknown, context: ToolHandlerContext) => Promise<string>;

export const handlers: Record<string, ToolHandler> = {
${entries}
};
`;
}

function buildSingleHandler(toolName: string): string {
  const safe = toSafeIdentifier(toolName);
  return `import type { ToolHandler } from "./index.js";

export const ${safe}: ToolHandler = async (args) => {
  return [
    "Stub handler executed successfully.",
    "tool=${toolName}",
    "args=" + JSON.stringify(args),
  ].join("\\n");
};
`;
}

function buildGeneratedToolsModule(tools: BuildResult["tools"]): string {
  const toolsCode = tools
    .map((tool) => {
      const schemaCode = jsonSchemaPropertiesToZodObject(tool.inputSchema);
      return `  {
    name: ${JSON.stringify(tool.name)},
    description: ${JSON.stringify(tool.description)},
    inputSchema: ${schemaCode}
  }`;
    })
    .join(",\n");

  return `import * as z from "zod/v4";

export interface GeneratedTool {
  name: string;
  description: string;
  inputSchema: Record<string, z.ZodTypeAny>;
}

export const generatedTools: GeneratedTool[] = [
${toolsCode}
];
`;
}

function buildServerModule(defaultTransport: TransportMode): string {
  return `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { createMcpExpressApp } from "@modelcontextprotocol/sdk/server/express.js";
import { generatedTools } from "./generated-tools.js";
import { handlers } from "./handlers/index.js";

type TransportMode = "stdio" | "http" | "both";

function createServer(): McpServer {
  const server = new McpServer({
    name: "generated-skill2mcp-server",
    version: "0.1.0",
  });

  for (const tool of generatedTools) {
    server.registerTool(
      tool.name,
      {
        description: tool.description,
        inputSchema: tool.inputSchema,
      },
      async (args) => {
        const handler = handlers[tool.name];
        const text = await handler(args, { toolName: tool.name });

        return {
          content: [
            {
              type: "text",
              text,
            },
          ],
        };
      },
    );
  }

  return server;
}

async function startStdioServer(): Promise<void> {
  const server = createServer();
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write("MCP stdio server running\\n");
}

function startHttpServer(port: number): void {
  const app = createMcpExpressApp();

  app.post("/mcp", async (req: any, res: any) => {
    const server = createServer();

    try {
      const transport = new StreamableHTTPServerTransport({
        sessionIdGenerator: undefined,
      });

      await server.connect(transport);
      await transport.handleRequest(req, res, req.body);

      res.on("close", () => {
        void transport.close();
        void server.close();
      });
    } catch (error) {
      if (!res.headersSent) {
        res.status(500).json({
          jsonrpc: "2.0",
          error: {
            code: -32603,
            message: error instanceof Error ? error.message : "Internal server error",
          },
          id: null,
        });
      }
    }
  });

  app.get("/mcp", (_req: any, res: any) => {
    res.status(405).set("Allow", "POST").send("Method Not Allowed");
  });

  app.delete("/mcp", (_req: any, res: any) => {
    res.status(405).set("Allow", "POST").send("Method Not Allowed");
  });

  app.listen(port, (error?: Error) => {
    if (error) {
      process.stderr.write("Failed to start HTTP server: " + error.message + "\\n");
      process.exit(1);
    }
    process.stderr.write("MCP HTTP server running on http://localhost:" + port + "/mcp\\n");
  });
}

function resolveTransportMode(): TransportMode {
  const transportArgIndex = process.argv.indexOf("--transport");
  const argValue = transportArgIndex >= 0 ? process.argv[transportArgIndex + 1] : undefined;
  const envValue = process.env.MCP_TRANSPORT;
  const value = (argValue ?? envValue ?? ${JSON.stringify(defaultTransport)}) as TransportMode;

  if (value === "stdio" || value === "http" || value === "both") {
    return value;
  }

  return ${JSON.stringify(defaultTransport)};
}

async function main(): Promise<void> {
  const transport = resolveTransportMode();
  const port = Number(process.env.PORT ?? "3000");

  if (transport === "stdio") {
    await startStdioServer();
    return;
  }

  if (transport === "http") {
    startHttpServer(port);
    return;
  }

  startHttpServer(port);
  await startStdioServer();
}

main().catch((error) => {
  process.stderr.write((error instanceof Error ? error.message : String(error)) + "\\n");
  process.exit(1);
});
`;
}

async function writeArtifacts(baseDir: string, files: BuildArtifact[]): Promise<void> {
  await mkdir(baseDir, { recursive: true });

  for (const file of files) {
    const absolutePath = path.join(baseDir, file.path);
    await mkdir(path.dirname(absolutePath), { recursive: true });
    await writeFile(absolutePath, file.content, "utf8");
  }
}

function collectDiagnostics(diagnostics: ParseDiagnostic[]): { hasErrors: boolean } {
  return {
    hasErrors: diagnostics.some((diagnostic) => diagnostic.level === "error"),
  };
}

export async function buildProject(inputPath: string, options: BuildCommandOptions): Promise<BuildResult | { error: string; diagnostics: ParseDiagnostic[] }> {
  const parsed = await parseInputPath(inputPath, options.mode);
  if ("error" in parsed) {
    return {
      error: parsed.error,
      diagnostics: parsed.diagnostics as ParseDiagnostic[],
    };
  }

  const diagnostics: ParseDiagnostic[] = [];
  const tools = parsed.results.map((entry) => {
    const mapped = mapSkillToTool(entry.document);
    diagnostics.push(...entry.diagnostics, ...mapped.diagnostics);
    return mapped.tool;
  });

  const status = collectDiagnostics(diagnostics);
  if (options.mode === "strict" && status.hasErrors) {
    return {
      error: "Build aborted because strict mode found validation errors.",
      diagnostics,
    };
  }

  const files: BuildArtifact[] = [];

  files.push({ path: "package.json", content: buildPackageJson(options.transport) });
  files.push({ path: "tsconfig.json", content: buildTsConfig() });
  files.push({ path: "README.md", content: buildReadme(options.transport) });
  files.push({ path: "tools.json", content: buildToolsJson(tools) });
  files.push({ path: "src/generated-tools.ts", content: buildGeneratedToolsModule(tools) });
  files.push({ path: "src/server.ts", content: buildServerModule(options.transport) });

  const handlerToolNames = tools.map((tool) => tool.name);
  files.push({ path: "src/handlers/index.ts", content: buildHandlersIndex(handlerToolNames) });

  for (const toolName of handlerToolNames) {
    files.push({
      path: `src/handlers/${toSafeIdentifier(toolName)}.ts`,
      content: buildSingleHandler(toolName),
    });
  }

  await writeArtifacts(options.outDir, files);

  return {
    tools,
    diagnostics,
    files,
  };
}
